### ISSUE TITLE
Dependency resque-lock-timeout not installed with 'bundle install'

### ISSUE THREAD

**Issue by vpuzzella** [agibralter/ts-resque-delta#1]
Works fine with 'gem install' though.

Thanks for the great software! Loving it!

**Comment by agibralter** [comment]
Do you get this with version 0.0.4?

**Comment by vpuzzella** [comment]
That did the trick. I was using 0.0.1 as stated in the documentation.
Thanks!

**Comment by agibralter** [comment]
Ahh I need to update that. Thanks!
