### ISSUE TITLE
"undefined method `indexes'" error with Riddle 1.5.0 / ts-resque-delta 1.1.4

### ISSUE THREAD

**Issue by tjoneseng** [agibralter/ts-resque-delta#10]
It looks like the Riddle API changed in 1.5.0 and broke ts-resque-delta.  More info at https://github.com/freelancing-god/thinking-sphinx/issues/301.

$ rake ts:index --trace
*\* Invoke ts:index (first_time)
*\* Invoke thinking_sphinx:index (first_time)
*\* Invoke thinking_sphinx:app_env (first_time)
*\* Execute thinking_sphinx:app_env
*\* Invoke environment (first_time)
*\* Execute environment
*\* Invoke thinking_sphinx:lock_deltas (first_time)
*\* Execute thinking_sphinx:lock_deltas
rake aborted!
undefined method `indexes' for #<Riddle::Configuration:0x104e45b88>
.../ts-resque-delta-1.1.4/lib/thinking_sphinx/deltas/resque_delta/tasks.rb:10:in`sphinx_indexes'
.../gems/ts-resque-delta-1.1.4/lib/thinking_sphinx/deltas/resque_delta/tasks.rb:30
...

**Comment by agibralter** [comment]
Ah.. It looks like I'm going to have to split ts-resque-delta into two branches. One to suport TS 1.x and one for TS 2.x... I'll try to release them asap.

**Comment by tjoneseng** [comment]
I was actually using TS 1.x when I ran into this.  I think it's a Riddle issue, not a TS issue.

**Comment by agibralter** [comment]
hmm yeah I read through https://github.com/freelancing-god/thinking-sphinx/issues/301 -- it seems like riddle 1.5.0 requires 2.0.10.

What I was thinking was having a branch/gem release that supports the latest version of TS/Riddle. Then I'll release another gem that requires TS >~ 1.0 and Riddle >~ 1.4.0

/cc @freelancing-god

**Comment by pat** [comment]
Riddle 1.5 has changed indexes (e.g.: plural of index) to indices, to distinguish that beside indexes (the action). TS 1.4.10 and 2.0.10 require Riddle 1.5. I guess this does make life a bit harder for the delta gems (I've not modified my datetime/delayed-deltas yet).

So, next release of ts-resque-delta could perhaps have an additional requirement of riddle >= 1.5? That's what I've done for the flying-sphinx gem.

**Comment by agibralter** [comment]
Ok I released a new version that depends on Riddle >= 1.5.

@barbarcodes for older versions of TS (< 2.0.10), please be specific in your Gemfile about which versions of TS, Riddle, and ts-resque-delta you need.
