### ISSUE TITLE
Remaining combined job errata

### ISSUE THREAD

**Issue by ryansch** [agibralter/ts-resque-delta#13]
I'll get some tests in place for the core indexing using the original rake task and fix the lock all deltas stuff.

Do we want to extend this approach to flying sphinx?  It should be compatible.

I'm not seeing any further EAGAIN errors after upgrading hiredis to the latest version.  See: https://github.com/ezmobius/redis-rb/issues/160

**Comment by agibralter** [comment]
Yeah no EAGAIN errors here either :)
