### ISSUE TITLE
ts-resque-delta is not initializing

### ISSUE THREAD

**Issue by Bek** [agibralter/ts-resque-delta#4]
I am getting:

NameError: uninitialized constant ThinkingSphinx::Deltas::ResqueDelta

when I do "Message.search 'something' " with console. "rake ts:rebuild " gives this error:

rake aborted!
uninitialized constant ThinkingSphinx::Deltas::ResqueDelta

My model index task is here:

  define_index do
    indexes text
    set_property :delta => ThinkingSphinx::Deltas::ResqueDelta
  end 

Rakefile looks like this:

require File.expand_path('../config/application', **FILE**)
require 'rake'
require 'thinking_sphinx/deltas/resque_delta/tasks'
SampleApp::Application.load_tasks

What could be wrong, my resque and redis were working before, and ts:index wasn't giving me any trouble?

**Comment by agibralter** [comment]
What does your `Gemfile` look like?

```
gem("ts-resque-delta", "0.0.6", :require => "thinking_sphinx/deltas/resque_delta")
```

Also, there are no Rake tasks for ts-resque-delta--sorry, the documentation is incorrect--so you don't need

```
require 'thinking_sphinx/deltas/resque_delta/tasks'
```

in your Rakefile. https://github.com/agibralter/ts-resque-delta/blob/master/lib/thinking_sphinx/deltas/resque_delta/tasks.rb

Basically you just need to ensure that you have a Resque job that is processing the `:ts_delta` queue.

**Comment by agibralter** [comment]
Oops, scratch the second part of that... sorry. `thinking_sphinx/deltas/resque_delta/tasks'` includes code that cancels delta jobs when the main indexer is running. Anyway, the `Gemfile` part of my comment still applies though... what does yours look like?

**Comment by Bek** [comment]
Thanks a bunch for a prompt response! ":require => "thinking_sphinx/deltas/resque_delta" was missing. It is running now.  Originally it was there as in the documentation, but "x.x.x" gave an error and I left it as gem "ts-resque-delta". Great gem, thanks again!

**Comment by agibralter** [comment]
Yeah... By `"x.x.x"` I meant "put in the latest version of ts-resque-delta"... i.e. `"0.0.6"`. Sorry... lazy documentation.
