### ISSUE TITLE
why make the Gemfile entry require a `:require`?

### ISSUE THREAD

**Issue by agibralter** [agibralter/ts-resque-delta#7]
Is there any good reason why this has been a convention in TS-related gems:

```
 gem 'ts-resque-delta', '1.0.0', :require => 'thinking_sphinx/deltas/resque_delta'
```

as opposed to:

```
 gem 'ts-resque-delta', '1.0.0'
```

**Comment by agibralter** [comment]
@freelancing-god -- any thoughts?

**Comment by pat** [comment]
`ts-resque-delta` (and equivalents) are abbreviations, I feel, hence why I used the full path. Now, I'm not so fussed - for example, with Thinking Sphinx I added `lib/thinking-sphinx.rb`, so you don't need to specify a :require option. I see no issue with doing something similar here.

**Comment by agibralter** [comment]
Yeah, I'm going to change it and update the README. I think it's more elegant to just have people specify the gem and get the most desired behavior. Plus with Rails 3 now, we can automatically load Rake tasks.

**Comment by pat** [comment]
Yeah, about time with the Rake task stuff - Merb had that from early on.
