### ISSUE TITLE
Illformed gemspec due broken RubyGems

### ISSUE THREAD

**Issue by luislavena** [agibralter/ts-resque-delta#8]
Hello,

It seems the latest gem (1.1.1) has illformed gemspec:

```
Invalid gemspec in [/data/app/shared/bundled_gems/ruby/1.8/specifications/ts-resque-delta-1.1.1.gemspec]: Illformed requirement ["#<YAML::Syck::DefaultKey:0xb6488ef4> 0.8.7"]
```

This happens due a broken version of RubyGems:

http://blog.rubygems.org/2011/08/31/shaving-the-yaml-yak.html

Some servers cannot be upgraded to latest version of RubyGems to workaround this issue, so regenerating the gemspec should solve it.

Would you mind bumping it so others can solve this issue?

Thank you.

**Comment by agibralter** [comment]
I'm not sure I follow. All I have to do is bump the version and regenerate the spec?

**Comment by luislavena** [comment]
Yes please, if you upgraded to RubyGems 1.8.x when generated those gems, please upgrade to latest (1.8.11), bump the version and generate the gems again.

Will be much appreciated for those locked to RubyGems < 1.8.x on some servers :-)

**Comment by agibralter** [comment]
Ahhh ok. Done: http://rubygems.org/gems/ts-resque-delta/versions/1.1.2. Thanks for pointing that out.

**Comment by gaganawhad** [comment]
I am getting this problem even for version 1.1.2

**Comment by agibralter** [comment]
Hmm I'm not so sure what to do about this -- what are the best practices for this issue? I generally keep my ruby gems pretty up-to-date. What version of rubygems are you guys using?

**Comment by pat** [comment]
For me I found generating the gemspec/gem in Ruby 1.8.7 did the trick - so maybe it's worth trying that? Definitely try installing it locally in 1.8.7 before publishing to rubygems.org

**Comment by agibralter** [comment]
@gaganawhad -- how is 1.1.3 for you?

**Comment by gaganawhad** [comment]
Looks like that is working. Thanks! Appreciate what you do

**Comment by agibralter** [comment]
:) Awesome -- sorry for all the trouble.

**Comment by luislavena** [comment]
> :) Awesome -- sorry for all the trouble.

Thank you so much!
